// <auto-generated />
using System;
using AeroAdapter.Infrastructure.Persistences;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AeroAdapter.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AeroAdapter.Infrastructure.Persistences.Entities.AccessDatabaseSpecification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<short>("b_act_date")
                        .HasColumnType("smallint");

                    b.Property<short>("b_apb_location")
                        .HasColumnType("smallint");

                    b.Property<short>("b_asset_group")
                        .HasColumnType("smallint");

                    b.Property<short>("b_deact_date")
                        .HasColumnType("smallint");

                    b.Property<short>("b_issue_code")
                        .HasColumnType("smallint");

                    b.Property<short>("b_support_time_apb")
                        .HasColumnType("smallint");

                    b.Property<short>("b_upgrade_date")
                        .HasColumnType("smallint");

                    b.Property<short>("b_use_limit")
                        .HasColumnType("smallint");

                    b.Property<short>("b_user_level")
                        .HasColumnType("smallint");

                    b.Property<short>("b_vacation_date")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("mac")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("n_alvl")
                        .HasColumnType("smallint");

                    b.Property<short>("n_alvl_use4arg")
                        .HasColumnType("smallint");

                    b.Property<short>("n_card")
                        .HasColumnType("smallint");

                    b.Property<short>("n_escort_timeout")
                        .HasColumnType("smallint");

                    b.Property<short>("n_host_response_timeout")
                        .HasColumnType("smallint");

                    b.Property<short>("n_multi_card_timeout")
                        .HasColumnType("smallint");

                    b.Property<short>("n_pin_digits")
                        .HasColumnType("smallint");

                    b.Property<short>("n_tz")
                        .HasColumnType("smallint");

                    b.Property<short>("scp_id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("id");

                    b.ToTable("AccessDatabaseSpecifications");

                    b.HasData(
                        new
                        {
                            id = 1,
                            b_act_date = (short)2,
                            b_apb_location = (short)1,
                            b_asset_group = (short)0,
                            b_deact_date = (short)2,
                            b_issue_code = (short)1,
                            b_support_time_apb = (short)1,
                            b_upgrade_date = (short)1,
                            b_use_limit = (short)1,
                            b_user_level = (short)7,
                            b_vacation_date = (short)1,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            mac = "",
                            n_alvl = (short)8,
                            n_alvl_use4arg = (short)0,
                            n_card = (short)1000,
                            n_escort_timeout = (short)15,
                            n_host_response_timeout = (short)5,
                            n_multi_card_timeout = (short)15,
                            n_pin_digits = (short)324,
                            n_tz = (short)64,
                            scp_id = (short)0,
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AeroAdapter.Infrastructure.Persistences.Entities.CreateChannel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<short>("baudrate")
                        .HasColumnType("smallint");

                    b.Property<short>("c_model_id")
                        .HasColumnType("smallint");

                    b.Property<short>("c_port")
                        .HasColumnType("smallint");

                    b.Property<short>("c_rts_mode")
                        .HasColumnType("smallint");

                    b.Property<short>("c_type")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<short>("n_channel_id")
                        .HasColumnType("smallint");

                    b.Property<short>("timer_1")
                        .HasColumnType("smallint");

                    b.Property<short>("timer_2")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("id");

                    b.ToTable("CreateChannels");

                    b.HasData(
                        new
                        {
                            id = 1,
                            baudrate = (short)0,
                            c_model_id = (short)0,
                            c_port = (short)0,
                            c_rts_mode = (short)0,
                            c_type = (short)7,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            n_channel_id = (short)1,
                            timer_1 = (short)3000,
                            timer_2 = (short)0,
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AeroAdapter.Infrastructure.Persistences.Entities.DriverConfiguration", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<short>("baudrate")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("mac")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("msp1_number")
                        .HasColumnType("smallint");

                    b.Property<short>("n_dialect")
                        .HasColumnType("smallint");

                    b.Property<short>("n_protocol")
                        .HasColumnType("smallint");

                    b.Property<short>("port_number")
                        .HasColumnType("smallint");

                    b.Property<short>("reply_time")
                        .HasColumnType("smallint");

                    b.Property<short>("scp_id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("id");

                    b.ToTable("DriverConfigurations");

                    b.HasData(
                        new
                        {
                            id = 1,
                            baudrate = (short)-1,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            mac = "",
                            msp1_number = (short)0,
                            n_dialect = (short)0,
                            n_protocol = (short)0,
                            port_number = (short)3,
                            reply_time = (short)0,
                            scp_id = (short)0,
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AeroAdapter.Infrastructure.Persistences.Entities.ElevatorAccessLevelSpecification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("mac")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("max_ealvl")
                        .HasColumnType("smallint");

                    b.Property<short>("max_floors")
                        .HasColumnType("smallint");

                    b.Property<short>("scp_id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("id");

                    b.ToTable("ElevatorAccessLevelSpecifications");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            mac = "",
                            max_ealvl = (short)256,
                            max_floors = (short)128,
                            scp_id = (short)0,
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AeroAdapter.Infrastructure.Persistences.Entities.InputPointSpecification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<short>("debounce")
                        .HasColumnType("smallint");

                    b.Property<short>("hold_time")
                        .HasColumnType("smallint");

                    b.Property<short>("icvt_num")
                        .HasColumnType("smallint");

                    b.Property<short>("input_number")
                        .HasColumnType("smallint");

                    b.Property<string>("mac")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("scp_id")
                        .HasColumnType("smallint");

                    b.Property<short>("sio_number")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("id");

                    b.ToTable("InputPointSpecifications");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            debounce = (short)2,
                            hold_time = (short)5,
                            icvt_num = (short)0,
                            input_number = (short)0,
                            mac = "",
                            scp_id = (short)0,
                            sio_number = (short)0,
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AeroAdapter.Infrastructure.Persistences.Entities.Scp", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("mac")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("scp_id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("id");

                    b.ToTable("Scps");
                });

            modelBuilder.Entity("AeroAdapter.Infrastructure.Persistences.Entities.ScpDeviceSpecification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<short>("gmt_offset")
                        .HasColumnType("smallint");

                    b.Property<string>("mac")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("n_acr")
                        .HasColumnType("smallint");

                    b.Property<short>("n_alvl")
                        .HasColumnType("smallint");

                    b.Property<short>("n_cp")
                        .HasColumnType("smallint");

                    b.Property<short>("n_dst_id")
                        .HasColumnType("smallint");

                    b.Property<short>("n_hol")
                        .HasColumnType("smallint");

                    b.Property<short>("n_language")
                        .HasColumnType("smallint");

                    b.Property<short>("n_mp")
                        .HasColumnType("smallint");

                    b.Property<short>("n_mpg")
                        .HasColumnType("smallint");

                    b.Property<short>("n_msp1_port")
                        .HasColumnType("smallint");

                    b.Property<short>("n_oper_mode")
                        .HasColumnType("smallint");

                    b.Property<short>("n_proc")
                        .HasColumnType("smallint");

                    b.Property<short>("n_sio")
                        .HasColumnType("smallint");

                    b.Property<int>("n_tran_limit")
                        .HasColumnType("integer");

                    b.Property<int>("n_transcations")
                        .HasColumnType("integer");

                    b.Property<short>("n_trgr")
                        .HasColumnType("smallint");

                    b.Property<short>("n_tz")
                        .HasColumnType("smallint");

                    b.Property<short>("oper_type")
                        .HasColumnType("smallint");

                    b.Property<short>("scp_id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("id");

                    b.ToTable("ScpDeviceSpecifications");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            gmt_offset = (short)-25200,
                            mac = "",
                            n_acr = (short)64,
                            n_alvl = (short)32000,
                            n_cp = (short)388,
                            n_dst_id = (short)0,
                            n_hol = (short)255,
                            n_language = (short)0,
                            n_mp = (short)615,
                            n_mpg = (short)128,
                            n_msp1_port = (short)3,
                            n_oper_mode = (short)0,
                            n_proc = (short)1024,
                            n_sio = (short)33,
                            n_tran_limit = 60000,
                            n_transcations = 60000,
                            n_trgr = (short)1024,
                            n_tz = (short)255,
                            oper_type = (short)1,
                            scp_id = (short)0,
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AeroAdapter.Infrastructure.Persistences.Entities.SioPanelConfiguration", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<short>("address")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<short>("emax")
                        .HasColumnType("smallint");

                    b.Property<short>("enable")
                        .HasColumnType("smallint");

                    b.Property<short>("flags")
                        .HasColumnType("smallint");

                    b.Property<string>("mac")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("model")
                        .HasColumnType("smallint");

                    b.Property<short>("n_inputs")
                        .HasColumnType("smallint");

                    b.Property<short>("n_outputs")
                        .HasColumnType("smallint");

                    b.Property<short>("n_readers")
                        .HasColumnType("smallint");

                    b.Property<short>("n_sio_next_in")
                        .HasColumnType("smallint");

                    b.Property<short>("n_sio_next_out")
                        .HasColumnType("smallint");

                    b.Property<short>("n_sio_next_rdr")
                        .HasColumnType("smallint");

                    b.Property<short>("port")
                        .HasColumnType("smallint");

                    b.Property<short>("scp_id")
                        .HasColumnType("smallint");

                    b.Property<short>("sio_number")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("id");

                    b.ToTable("SioPanelConfigurations");

                    b.HasData(
                        new
                        {
                            id = 1,
                            address = (short)0,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            emax = (short)3,
                            enable = (short)1,
                            flags = (short)0,
                            mac = "",
                            model = (short)196,
                            n_inputs = (short)7,
                            n_outputs = (short)4,
                            n_readers = (short)4,
                            n_sio_next_in = (short)-1,
                            n_sio_next_out = (short)-1,
                            n_sio_next_rdr = (short)-1,
                            port = (short)0,
                            scp_id = (short)0,
                            sio_number = (short)0,
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AeroAdapter.Infrastructure.Persistences.Entities.SystemLevelSpecification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<short>("b_direct_mode")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<short>("debug_rq")
                        .HasColumnType("smallint");

                    b.Property<short>("n_debug_arg")
                        .HasColumnType("smallint");

                    b.Property<short>("n_holidays")
                        .HasColumnType("smallint");

                    b.Property<short>("n_ports")
                        .HasColumnType("smallint");

                    b.Property<short>("n_scps")
                        .HasColumnType("smallint");

                    b.Property<short>("n_timezones")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("id");

                    b.ToTable("SystemLevelSpecifications");

                    b.HasData(
                        new
                        {
                            id = 1,
                            b_direct_mode = (short)1,
                            created_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            debug_rq = (short)0,
                            n_debug_arg = (short)0,
                            n_holidays = (short)0,
                            n_ports = (short)1024,
                            n_scps = (short)1024,
                            n_timezones = (short)0,
                            updated_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AeroAdapter.Infrastructure.Persistences.Entities.WriterAudit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("command")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("command_code")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<bool>("is_nak")
                        .HasColumnType("boolean");

                    b.Property<string>("mac")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("received_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("scp_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("send_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("tag")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("id");

                    b.ToTable("WriterAudits");
                });
#pragma warning restore 612, 618
        }
    }
}
